clean up dockerfile renv runtime

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,40 +7,45 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Lint Quarto Notebooks
-      run: |
-        find ./project/docs/ -name "*.qmd" -type f -exec python meta/testing/linter.py {} \;
-      if: ${{ failure() }}
-      continue-on-error: true
-    - name: Fail on Linting Error
-      if: ${{ steps.lint.outputs.linting_failed == 'true' }}
-      run: echo "Linting errors - check output from prior stage."
-      #run: exit 1
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
-    - name: Build and export
-      uses: docker/build-push-action@v4
-      with:
-        context: .
-        file: .dockerfile
-        tags: my-app-image:latest
-        outputs: type=local,dest=./artifacts
-    - name: Display structure of downloaded files
-      run: ls -R ./artifacts
-    - name: Deploy to GitHub Pages
-      uses: peaceiris/actions-gh-pages@v3
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./artifacts/artifacts/build
-        publish_branch: gh-pages
-    - name: Remove HTML files
-      run: |
-        find ./artifacts -name '*.html' -exec rm {} \;
-    - name: Deploy remaining artifacts
-      uses: peaceiris/actions-gh-pages@v3
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./artifacts
-        publish_branch: artifacts
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Lint Quarto Notebooks
+        run: |
+          find ./project/docs/ -name "*.qmd" -type f -exec python meta/testing/linter.py {} \; > lint_output.txt
+          if [ -s lint_output.txt ]; then
+            echo "linting_failed=true" >> $GITHUB_OUTPUT
+            cat lint_output.txt
+            exit 1
+          fi
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Build and export
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          file: .dockerfile
+          tags: my-app-image:latest
+          outputs: type=local,dest=./artifacts
+        
+      - name: Display structure of downloaded files
+        run: ls -R ./artifacts
+
+      - name: Deploy to GitHub Pages
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./artifacts/artifacts/build
+          publish_branch: gh-pages
+
+      - name: Remove HTML files
+        run: |
+          find ./artifacts -name '*.html' -exec rm {} \;
+          
+      - name: Deploy remaining artifacts
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./artifacts
+          publish_branch: artifacts
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,31 +6,36 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Lint Quarto Notebooks
-      run: |
-        find ./project/docs/ -name "*.qmd" -type f -exec python meta/testing/linter.py {} \;
-      if: ${{ failure() }}
-      continue-on-error: true
-    - name: Fail on Linting Error
-      if: ${{ steps.lint.outputs.linting_failed == 'true' }}
-      run: echo "Linting errors - check output from prior stage."
-      #run: exit 1
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
-    - name: Build and export
-      uses: docker/build-push-action@v4
-      with:
-        context: .
-        file: .dockerfile
-        tags: my-app-image:latest
-        outputs: type=local,dest=./artifacts
-    - name: Display structure of downloaded files
-      run: ls -R ./artifacts
-    - name: Upload Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: Render
-        path: ./artifacts
-        retention-days: 5
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Lint Quarto Notebooks
+        id: lint
+        run: |
+          find ./project/docs/ -name "*.qmd" -type f -exec python meta/testing/linter.py {} \; > lint_output.txt
+          if [ -s lint_output.txt ]; then
+            echo "linting_failed=true" >> $GITHUB_OUTPUT
+            cat lint_output.txt
+            exit 1
+          fi
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Build and export
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          file: .dockerfile
+          tags: my-app-image:latest
+          outputs: type=local,dest=./artifacts
+
+      - name: Display structure of downloaded files
+        run: ls -R ./artifacts
+
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: Render
+          path: ./artifacts
+          retention-days: 5
